wail-app/src/main/java/com/artemzin/android/wail/storage/WAILSettings.java
=> Wail settings optimization

wail-app/src/main/java/com/artemzin/android/wail/storage/WAILSettings.java, wail-app/src/main/java/com/artemzin/android/wail/ui/fragment/main/MainFragment.java, wail-app/src/main/java/com/artemzin/android/wail/util/LocaleUtil.java, wail-app/src/main/res/layout/fragment_main_settings.xml, wail-app/src/main/res/layout/fragment_non_authorized.xml, wail-app/src/main/res/values-de/strings.xml, wail-app/src/main/res/values-ru/strings.xml, wail-app/src/main/res/values/analytics.xml, wail-app/src/main/res/values/strings.xml, wail-app/src/main/res/values/strings_do_not_translate.xml, wail-app/src/main/res/values/styles_dark.xml, wail-app/src/main/res/values/styles_light.xml
I'm not a professional translator, but this is something to start with :)
resolves #77
=> Russian translation

wail-app/src/main/res/values-ru/strings.xml
@artem-zinnatullin, ok? :)
resolves #82
=> Improved russian translation

wail-app/src/main/res/layout/fragment_main_settings.xml, wail-app/src/main/res/values/attrs.xml, wail-app/src/main/res/values/colors.xml, wail-app/src/main/res/values/dimens.xml, wail-app/src/main/res/values/styles_dark.xml, wail-app/src/main/res/values/styles_light.xml, wail-app/src/main/res/values/themes.xml
=> Settings material design

wail-app/src/main/java/com/artemzin/android/wail/ui/fragment/settings/SettingsSoundNotificationsFragment.java, wail-app/src/main/java/com/artemzin/android/wail/ui/fragment/settings/SettingsStatusBarNotificationsFragment.java, wail-app/src/main/res/layout/fragment_main_settings.xml, wail-app/src/main/res/layout/fragment_settings_sound_notifications.xml, wail-app/src/main/res/layout/fragment_settings_status_bar_notifications.xml
=> settings restructuring

wail-app/build.gradle, wail-app/src/main/java/com/artemzin/android/wail/ui/fragment/dialogs/DialogFragmentWithNumberPicker.java, wail-app/src/main/java/com/artemzin/android/wail/ui/fragment/dialogs/DialogFragmentWithSeekBar.java, wail-app/src/main/java/com/artemzin/android/wail/ui/fragment/main/MainFragment.java, wail-app/src/main/java/com/artemzin/android/wail/ui/fragment/main/SettingsFragment.java, wail-app/src/main/res/layout/dialog_with_number_picker_fragment.xml, wail-app/src/main/res/layout/dialog_with_seek_bar_fragment.xml, wail-app/src/main/res/values/strings.xml
=> Material dialogs

wail-app/src/main/res/values-de/strings.xml
=> German translation.

wail-app/src/main/res/values-de/strings.xml
No idea, why it includes 2 older commits which were already merged though.
=> Improvements to German translation, incl. fix for #126

wail-app/src/main/res/values-ko/strings.xml, wail-app/src/main/res/values/strings_do_not_translate.xml
I added Korean language support.
=> Add Korean language support

.travis.yml
=> [WIP] Fix Travis CI build

wail-app/src/androidTest/java/com/artemzin/android/wail/test/unit/receiver/CommonMusicAppReceiverTest.java, wail-app/src/main/java/com/artemzin/android/wail/api/lastfm/model/request/LFTrackRequestModel.java, wail-app/src/main/java/com/artemzin/android/wail/service/WAILService.java, wail-app/src/main/java/com/artemzin/android/wail/storage/WAILSettings.java, wail-app/src/main/java/com/artemzin/android/wail/storage/db/TracksDBHelper.java, wail-app/src/main/java/com/artemzin/android/wail/storage/model/Track.java, wail-app/src/main/java/com/artemzin/android/wail/ui/fragment/dialogs/DialogFragmentWithSeekBar.java, wail-app/src/main/java/com/artemzin/android/wail/ui/fragment/main/SettingsFragment.java, wail-app/src/main/res/layout/fragment_main_settings.xml, wail-app/src/main/res/values-de/strings.xml, wail-app/src/main/res/values-ko/strings.xml, wail-app/src/main/res/values-ru/strings.xml, wail-app/src/main/res/values/strings.xml
@artem-zinnatullin, a review would be great.
Fixes #26
=> Re-implement scrobbling time logic

wail-app/src/main/java/com/artemzin/android/wail/notifications/StatusBarNotificationsManager.java, wail-app/src/main/java/com/artemzin/android/wail/storage/WAILSettings.java, wail-app/src/main/java/com/artemzin/android/wail/ui/fragment/settings/SettingsStatusBarNotificationsFragment.java, wail-app/src/main/res/layout/fragment_settings_status_bar_notifications.xml, wail-app/src/main/res/values-de/strings.xml, wail-app/src/main/res/values-ko/strings.xml, wail-app/src/main/res/values-ru/strings.xml, wail-app/src/main/res/values/strings.xml
=> Add option to use minimal priority notification

wail-app/build.gradle, wail-app/src/main/java/com/artemzin/android/wail/receiver/NotificationActionsReceiver.java, wail-app/src/main/java/com/artemzin/android/wail/service/WAILService.java, wail-app/src/main/java/com/artemzin/android/wail/storage/db/LovedTracksDBHelper.java, wail-app/src/main/java/com/artemzin/android/wail/ui/fragment/dialogs/DialogDecorator.java, wail-app/src/main/java/com/artemzin/android/wail/ui/fragment/dialogs/TrackActionsDialog.java, wail-app/src/main/java/com/artemzin/android/wail/ui/fragment/main/MainFragment.java, wail-app/src/main/java/com/artemzin/android/wail/ui/fragment/main/TracksListFragment.java, wail-app/src/main/res/layout/fragment_tracks_list.xml, wail-app/src/main/res/layout/track_list_item.xml, wail-app/src/main/res/values-de/strings.xml, wail-app/src/main/res/values-ko/strings.xml, wail-app/src/main/res/values-ru/strings.xml, wail-app/src/main/res/values/strings.xml, wail-app/src/main/res/values/styles_dark.xml, wail-app/src/main/res/values/styles_light.xml
=> Add option to love previously scrobbled track

wail-app/src/main/res/values-de/strings.xml
I hope I got all new strings. Good that all new strings also get into the German file so I just have to look for English in it.
=> German translation updated

wail-app/src/main/res/values-ko/strings.xml
Updated Korean translation. Issue #158
=> Update Korean translation

.travis.yml, gradle/wrapper/gradle-wrapper.properties, wail-app/build.gradle
- Update Gradle to 2.4
- Update target SDK to 22
- Update build tools to 22.0.1
=> Update build tools

wail-app/build.gradle, wail-app/proguard.cfg
Reverts artem-zinnatullin/android-wail-app#166
This caused the following exception:
```
06-30 20:08:33.553  20810-20810/com.artemzin.android.wail E/AndroidRuntime﹕ FATAL EXCEPTION: main
Process: com.artemzin.android.wail, PID: 20810
java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.view.View.findViewById(int)' on a null object reference
at com.artemzin.android.wail.ui.fragment.main.TracksListFragment$TracksSearchHandler.setSearchItem(TracksListFragment.java:417)
at com.artemzin.android.wail.ui.fragment.main.TracksListFragment.onCreateOptionsMenu(TracksListFragment.java:170)
at android.app.Fragment.performCreateOptionsMenu(Fragment.java:2133)
at android.app.FragmentManagerImpl.dispatchCreateOptionsMenu(FragmentManager.java:1943)
at …
```
=> Revert "Proguard"

wail-app/src/main/res/values-de/strings.xml
I added one too many "Sekunden". :-(
=> 1 "Sekunden" too much again.

wail-app/src/main/AndroidManifest.xml, wail-app/src/main/java/com/artemzin/android/wail/service/WAILService.java, wail-app/src/main/java/com/artemzin/android/wail/storage/db/AppDBManager.java, wail-app/src/main/java/com/artemzin/android/wail/storage/db/IgnoredPlayersDBHelper.java, wail-app/src/main/java/com/artemzin/android/wail/ui/activity/settings/SettingsIgnoredPlayersActivity.java, wail-app/src/main/java/com/artemzin/android/wail/ui/fragment/main/MainFragment.java, wail-app/src/main/java/com/artemzin/android/wail/ui/fragment/main/SettingsFragment.java, wail-app/src/main/java/com/artemzin/android/wail/ui/fragment/settings/SettingsIgnoredPlayersFragment.java, wail-app/src/main/res/layout/activity_settings_ignored_players.xml, wail-app/src/main/res/layout/fragment_main.xml, wail-app/src/main/res/layout/fragment_main_settings.xml, wail-app/src/main/res/layout/fragment_settings_ignored_players.xml, wail-app/src/main/res/layout/settings_ignored_players_item_layout.xml, wail-app/src/main/res/values-de/strings.xml, wail-app/src/main/res/values-ko/strings.xml, wail-app/src/main/res/values-ru/strings.xml, wail-app/src/main/res/values/attrs.xml, wail-app/src/main/res/values/strings.xml, wail-app/src/main/res/values/styles_dark.xml, wail-app/src/main/res/values/styles_light.xml, wail-app/src/main/res/values/themes.xml
I just reverted #155 here for now.
=> Reintroduce "ignore player" functionality

build.gradle
Upgrade grade from1.2.2 to 1.2.3
=> Upgrade to gradle 1.2.3

wail-app/src/main/java/com/artemzin/android/wail/service/WAILService.java
This change will prevent tracks without title or artist to be added to the database. And also, if such tracks were already added, it will be removed before scrobbling.
@artem-zinnatullin, please take a look.
=> Fix issue 177
